// Action types for Cards
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
export const FETCH_CARDS_FAILURE = 'FETCH_CARDS_FAILURE';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FAILURE = 'ADD_CARD_FAILURE';
export const EDIT_CARD_SUCCESS = 'EDIT_CARD_SUCCESS';
export const EDIT_CARD_FAILURE = 'EDIT_CARD_FAILURE';
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';
export const DELETE_CARD_FAILURE = 'DELETE_CARD_FAILURE';
export const MOVE_CARD_SUCCESS = 'MOVE_CARD_SUCCESS';
export const MOVE_CARD_FAILURE = 'MOVE_CARD_FAILURE';
export const FETCH_CARDS = 'FETCH_CARDS'; 
export const ADD_CARD = 'ADD_CARD';
export const EDIT_CARD = 'EDIT_CARD';
export const DELETE_CARD = 'DELETE_CARD';
export const MOVE_CARD = 'MOVE_CARD';
export const UPDATE_CARDS_AFTER_DELETE = 'UPDATE_CARDS_AFTER_DELETE';

// Action types for Buckets
export const FETCH_BUCKETS_SUCCESS = 'FETCH_BUCKETS_SUCCESS';
export const FETCH_BUCKETS_FAILURE = 'FETCH_BUCKETS_FAILURE';
export const ADD_BUCKET_SUCCESS = 'ADD_BUCKET_SUCCESS';
export const ADD_BUCKET_FAILURE = 'ADD_BUCKET_FAILURE';
export const EDIT_BUCKET_SUCCESS = 'EDIT_BUCKET_SUCCESS';
export const EDIT_BUCKET_FAILURE = 'EDIT_BUCKET_FAILURE';
export const DELETE_BUCKET_SUCCESS = 'DELETE_BUCKET_SUCCESS';
export const DELETE_BUCKET_FAILURE = 'DELETE_BUCKET_FAILURE';
export const ADD_BUCKET = 'ADD_BUCKET';
export const EDIT_BUCKET = 'EDIT_BUCKET';
export const DELETE_BUCKET = 'DELETE_BUCKET';
export const FETCH_BUCKETS= 'FETCH_BUCKETS'; 

// History action types
export const ADD_CARD_TO_HISTORY_SUCCESS = 'ADD_CARD_TO_HISTORY_SUCCESS';
export const ADD_CARD_TO_HISTORY_FAILURE = 'ADD_CARD_TO_HISTORY_FAILURE';
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS';
export const FETCH_HISTORY_FAILURE = 'FETCH_HISTORY_FAILURE';
